
server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:1hbl#QTmongo@106.14.237.78:27017/admin
      database: ersa
  redis:
    host: 106.14.237.78
    password: 1hbl#QT@redis
    port: 6379
    timeout: 5000ms
    database: 1

